"""rename department

Revision ID: 2a46c6b7edf8
Revises: 720f2e886b1a
Create Date: 2024-04-03 14:23:46.893183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a46c6b7edf8'
down_revision = '720f2e886b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')

    # ### end Alembic commands ###
