"""add Department

Revision ID: 720f2e886b1a
Revises: 5d5cba537317
Create Date: 2024-04-03 14:16:56.480349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720f2e886b1a'
down_revision = '5d5cba537317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
